Update pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -3,7 +3,7 @@
 
 BRANCH_NAME=$(git symbolic-ref --short HEAD)
 
-if ! npx --no-install validate-branch-name "$BRANCH_NAME"; then
-  echo "Invalid branch name"
-  exit 1
-fi
+# if ! npx --no-install validate-branch-name "$BRANCH_NAME"; then
+#   echo "Invalid branch name"
+#   exit 1
+# fi
